language: cpp
dist: bionic
services:
    - docker

before_install:
    # Install zig
    - sudo snap install zig --classic --edge

    # Pull wrk
    - docker pull williamyeh/wrk

script:
    # Test individual files
    - zig test -OReleaseSafe lib/zhp/app.zig

    # Run parser test
    - zig run --pkg-begin zhp lib/zhp/zhp.zig --pkg-end -OReleaseSafe tests/parser.zig

    # Make sure this repo builds
    - zig build -Drelease-safe=true install

    # Test example server
    #- zig run tests/bench.zig
