language: cpp
dist: bionic
services:
    - docker

before_install:
    # Install zig
    - sudo snap install zig --classic --edge

    # Make sure zig runs
    - zig --help

    # Pull wrk
    - docker pull williamyeh/wrk

    # Make sure this repo builds
    - zig build -Drelease-fast=true install

script:
    # Test request parser
    - zig test --release-fast lib/zhp/request.zig
    - zig test lib/zhp/mimetypes.zig

    # Test example server
    - zig run tests/bench.zig
