language: cpp
dist: bionic
services:
    - docker

before_install:
    # Install zig
    - sudo snap install zig --classic --edge

    # Make sure zig runs
    - zig --help

    # Pull wrk
    - docker pull williamyeh/wrk

script:
    # Test individual files
    - zig test --release-fast lib/zhp/status.zig
    - zig test --release-fast lib/zhp/headers.zig
    - zig test --release-fast lib/zhp/middleware.zig
    - zig test --release-fast lib/zhp/mimetypes.zig
    - zig test --release-fast lib/zhp/time/datetime.zig
    - zig test --release-fast lib/zhp/util.zig
    - zig test --release-fast lib/zhp/request.zig
    - zig test --release-fast lib/zhp/response.zig


    # Make sure this repo builds
    - zig build -Drelease-fast=true install

    # Test example server
    - zig run tests/bench.zig
