language: cpp
dist: bionic
before_install:
    # Install zig dependencies
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
    - sudo apt-get -q update
    - sudo apt-get -y install clang-9 libclang-9-dev llvm-9-dev

    # Install zig
    - git clone https://github.com/ziglang/zig
    - cd zig
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PREFIX -DZIG_STATIC=ON
    - make install

    # Make sure zig runs
    - zig --help

    # Make sure it builds
    - zig build

script:
    - zig test --Drelease-fast=safe lib/zhp/request.zig
